# Generated by Django 5.2.6 on 2025-09-06 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("emailid", models.CharField(max_length=122)),
                ("address", models.CharField(max_length=122)),
                ("query", models.CharField(max_length=150)),
                ("name", models.TextField()),
                ("date", models.DateField()),
            ],
        ),
    ]
